// This file generated by staff_codegen
// For more information please visit: http://code.google.com/p/staff/

#ifndef _FdExport_h_
#define _FdExport_h_

#include <list>
#include <string>
#include <staff/common/Optional.h>
#include <staff/common/WsdlTypes.h>
#include <staff/common/Nillable.h>
#include <staff/common/IService.h>

// *interface.elementFormDefault: qualified
// *interface.targetNamespace: http://fdisk.at/

  struct FdWsPrepareDataRequest;
  struct FdWsKurseRequest;
  struct ArrayOfArrayOfFdWsKurseRequestFilter;
  struct ArrayOfFdWsKurseRequestFilter;
  struct FdWsKurseRequestFilter;
  struct FdWsMitgliederRequest;
  struct ArrayOfArrayOfFdWsMitgliederRequestFilter;
  struct ArrayOfFdWsMitgliederRequestFilter;
  struct FdWsMitgliederRequestFilter;
  struct FdWsFWMitglieder144Request;
  struct ArrayOfArrayOfFdWsFWMitglieder144RequestFilter;
  struct ArrayOfFdWsFWMitglieder144RequestFilter;
  struct FdWsFWMitglieder144RequestFilter;
  struct FdWsDienstgradeRequest;
  struct ArrayOfArrayOfFdWsDienstgradeRequestFilter;
  struct ArrayOfFdWsDienstgradeRequestFilter;
  struct FdWsDienstgradeRequestFilter;
  struct FdWsAusbildungenRequest;
  struct ArrayOfArrayOfFdWsAusbildungenRequestFilter;
  struct ArrayOfFdWsAusbildungenRequestFilter;
  struct FdWsAusbildungenRequestFilter;
  struct FdWsFunktionenRequest;
  struct ArrayOfArrayOfFdWsFunktionenRequestFilter;
  struct ArrayOfFdWsFunktionenRequestFilter;
  struct FdWsFunktionenRequestFilter;
  struct FdWsFunktionaereRequest;
  struct ArrayOfArrayOfFdWsFunktionaereRequestFilter;
  struct ArrayOfFdWsFunktionaereRequestFilter;
  struct FdWsFunktionaereRequestFilter;
  struct FdWsInstanzenRequest;
  struct ArrayOfArrayOfFdWsInstanzenRequestFilter;
  struct ArrayOfFdWsInstanzenRequestFilter;
  struct FdWsInstanzenRequestFilter;
  struct FdWsFeuerwachenRequest;
  struct ArrayOfArrayOfFdWsFeuerwachenRequestFilter;
  struct ArrayOfFdWsFeuerwachenRequestFilter;
  struct FdWsFeuerwachenRequestFilter;
  struct FdWsSonderdiensteRequest;
  struct ArrayOfArrayOfFdWsSonderdiensteRequestFilter;
  struct ArrayOfFdWsSonderdiensteRequestFilter;
  struct FdWsSonderdiensteRequestFilter;
  struct FdWsFWInstanzen144Request;
  struct ArrayOfArrayOfFdWsFWInstanzen144RequestFilter;
  struct ArrayOfFdWsFWInstanzen144RequestFilter;
  struct FdWsFWInstanzen144RequestFilter;
  struct FdWsGeraeteRequest;
  struct ArrayOfArrayOfFdWsGeraeteRequestFilter;
  struct ArrayOfFdWsGeraeteRequestFilter;
  struct FdWsGeraeteRequestFilter;
  struct FdWsFahrzeugeRequest;
  struct ArrayOfArrayOfFdWsFahrzeugeRequestFilter;
  struct ArrayOfFdWsFahrzeugeRequestFilter;
  struct FdWsFahrzeugeRequestFilter;
  struct FdWsErreichbarkeitenFeuerwehrhaeuserRequest;
  struct ArrayOfArrayOfFdWsErreichbarkeitenFeuerwehrhaeuserRequestFilter;
  struct ArrayOfFdWsErreichbarkeitenFeuerwehrhaeuserRequestFilter;
  struct FdWsErreichbarkeitenFeuerwehrhaeuserRequestFilter;
  struct FdWsErreichbarkeitenPersonenRequest;
  struct ArrayOfArrayOfFdWsErreichbarkeitenPersonenRequestFilter;
  struct ArrayOfFdWsErreichbarkeitenPersonenRequestFilter;
  struct FdWsErreichbarkeitenPersonenRequestFilter;
  struct FdWsFeuerwehrhaeuserRequest;
  struct ArrayOfArrayOfFdWsFeuerwehrhaeuserRequestFilter;
  struct ArrayOfFdWsFeuerwehrhaeuserRequestFilter;
  struct FdWsFeuerwehrhaeuserRequestFilter;
  struct FdWsFeuerwehrGemeindenRequest;
  struct ArrayOfArrayOfFdWsFeuerwehrGemeindenRequestFilter;
  struct ArrayOfFdWsFeuerwehrGemeindenRequestFilter;
  struct FdWsFeuerwehrGemeindenRequestFilter;
  struct FdWsWasserdienstleistungsbewerbeRequest;
  struct ArrayOfArrayOfFdWsWasserdienstleistungsbewerbeRequestFilter;
  struct ArrayOfFdWsWasserdienstleistungsbewerbeRequestFilter;
  struct FdWsWasserdienstleistungsbewerbeRequestFilter;
  struct FdWsFeuerwehrleistungsbewerbeRequest;
  struct ArrayOfArrayOfFdWsFeuerwehrleistungsbewerbeRequestFilter;
  struct ArrayOfFdWsFeuerwehrleistungsbewerbeRequestFilter;
  struct FdWsFeuerwehrleistungsbewerbeRequestFilter;
  struct FdWsPrepareDataReturn;
  struct FdWsGetNextDataBlockReturn;
  struct ArrayOfFdWsFWMitglieder144Struct;
  struct TypeMapper;
  struct Writer;
  struct FdWsFWMitglieder144Struct;
  struct ArrayOfFdWsMitgliederStruct;
  struct FdWsMitgliederStruct;
  struct ArrayOfFdWsAusbildungenStruct;
  struct FdWsAusbildungenStruct;
  struct ArrayOfFdWsKurseStruct;
  struct FdWsKurseStruct;
  struct ArrayOfFdWsDienstgradeStruct;
  struct FdWsDienstgradeStruct;
  struct ArrayOfFdWsSonderdiensteStruct;
  struct FdWsSonderdiensteStruct;
  struct ArrayOfFdWsFunktionenStruct;
  struct FdWsFunktionenStruct;
  struct ArrayOfFdWsFunktionaereStruct;
  struct FdWsFunktionaereStruct;
  struct ArrayOfFdWsInstanzenStruct;
  struct FdWsInstanzenStruct;
  struct ArrayOfFdWsFWInstanzen144Struct;
  struct FdWsFWInstanzen144Struct;
  struct ArrayOfFdWsGeraeteStruct;
  struct FdWsGeraeteStruct;
  struct ArrayOfFdWsFahrzeugeStruct;
  struct FdWsFahrzeugeStruct;
  struct ArrayOfFdWsFeuerwachenStruct;
  struct FdWsFeuerwachenStruct;
  struct ArrayOfFdWsErreichbarkeitenFeuerwehrhaeuserStruct;
  struct FdWsErreichbarkeitenFeuerwehrhaeuserStruct;
  struct ArrayOfFdWsErreichbarkeitenPersonenStruct;
  struct FdWsErreichbarkeitenPersonenStruct;
  struct ArrayOfFdWsFeuerwehrhaeuserStruct;
  struct FdWsFeuerwehrhaeuserStruct;
  struct ArrayOfFdWsFeuerwehrGemeindenStruct;
  struct FdWsFeuerwehrGemeindenStruct;
  struct ArrayOfFdWsWasserdienstleistungsbewerbeStruct;
  struct FdWsWasserdienstleistungsbewerbeStruct;
  struct ArrayOfFdWsFeuerwehrleistungsbewerbeStruct;
  struct FdWsFeuerwehrleistungsbewerbeStruct;
  struct ArrayOfFdWsFeuerwehrleistungsbewerbePunkte;
  struct FdWsFeuerwehrleistungsbewerbePunkte;
  struct FdWsAuthorizeReturn;

  // *baseType: string
  // *renamed: true
  enum FdWsExportType
  {
    // *value: Feuerwachen
    FdWsExportType_Feuerwachen,
    // *value: Kurse
    FdWsExportType_Kurse,
    // *value: Ausbildungen
    FdWsExportType_Ausbildungen,
    // *value: Mitglieder
    FdWsExportType_Mitglieder,
    // *value: FWMitglieder144
    FdWsExportType_FWMitglieder144,
    // *value: Dienstgrade
    FdWsExportType_Dienstgrade,
    // *value: Funktionen
    FdWsExportType_Funktionen,
    // *value: Funktionaere
    FdWsExportType_Funktionaere,
    // *value: Instanzen
    FdWsExportType_Instanzen,
    // *value: Sonderdienste
    FdWsExportType_Sonderdienste,
    // *value: FWInstanzen144
    FdWsExportType_FWInstanzen144,
    // *value: FeuerwehrGemeinden
    FdWsExportType_FeuerwehrGemeinden,
    // *value: Feuerwehrhaeuser
    FdWsExportType_Feuerwehrhaeuser,
    // *value: ErreichbarkeitenFeuerwehrhaeuser
    FdWsExportType_ErreichbarkeitenFeuerwehrhaeuser,
    // *value: ErreichbarkeitenPersonen
    FdWsExportType_ErreichbarkeitenPersonen,
    // *value: Fahrzeuge
    FdWsExportType_Fahrzeuge,
    // *value: Geraete
    FdWsExportType_Geraete,
    // *value: Wasserdienstleistungsbewerbe
    FdWsExportType_Wasserdienstleistungsbewerbe,
    // *value: Feuerwehrleistungsbewerbe
    FdWsExportType_Feuerwehrleistungsbewerbe
  };

  // *baseType: string
  // *renamed: true
  enum FdWsKurseExpFilter
  {
    // *value: FdiskIdPersonen
    FdWsKurseExpFilter_FdiskIdPersonen,
    // *value: FdiskIdMitgliedschaften
    FdWsKurseExpFilter_FdiskIdMitgliedschaften,
    // *value: FdiskIdKurse
    FdWsKurseExpFilter_FdiskIdKurse
  };

  // *baseType: string
  // *renamed: true
  enum FdWsMitgliederExpFilter
  {
    // *value: FdiskIdMitglieder
    FdWsMitgliederExpFilter_FdiskIdMitglieder,
    // *value: FdiskIdPersonen
    FdWsMitgliederExpFilter_FdiskIdPersonen,
    // *value: FdiskIdDienstgrade
    FdWsMitgliederExpFilter_FdiskIdDienstgrade,
    // *value: Vorname
    FdWsMitgliederExpFilter_Vorname,
    // *value: Nachname
    FdWsMitgliederExpFilter_Nachname,
    // *value: Standesbuchnummer
    FdWsMitgliederExpFilter_Standesbuchnummer,
    // *value: InstanzNummer
    FdWsMitgliederExpFilter_InstanzNummer,
    // *value: LetzteAenderungVon
    FdWsMitgliederExpFilter_LetzteAenderungVon,
    // *value: LetzteAenderungBis
    FdWsMitgliederExpFilter_LetzteAenderungBis
  };

  // *baseType: string
  // *renamed: true
  enum FdWsFWMitglieder144ExpFilter
  {
    // *value: FdiskIdInstanzen
    FdWsFWMitglieder144ExpFilter_FdiskIdInstanzen,
    // *value: FdiskIdMitglieder
    FdWsFWMitglieder144ExpFilter_FdiskIdMitglieder,
    // *value: FdiskIdPersonen
    FdWsFWMitglieder144ExpFilter_FdiskIdPersonen,
    // *value: Vorname
    FdWsFWMitglieder144ExpFilter_Vorname,
    // *value: Nachname
    FdWsFWMitglieder144ExpFilter_Nachname,
    // *value: Standesbuchnummer
    FdWsFWMitglieder144ExpFilter_Standesbuchnummer,
    // *value: InstanzNummer
    FdWsFWMitglieder144ExpFilter_InstanzNummer
  };

  // *baseType: string
  // *renamed: true
  enum FdWsDienstgradeExpFilter
  {
    // *value: FdiskIdDienstgrade
    FdWsDienstgradeExpFilter_FdiskIdDienstgrade,
    // *value: Langbezeichnung
    FdWsDienstgradeExpFilter_Langbezeichnung,
    // *value: Kurzbezeichnung
    FdWsDienstgradeExpFilter_Kurzbezeichnung
  };

  // *baseType: string
  // *renamed: true
  enum FdWsAusbildungenExpFilter
  {
    // *value: FdiskIdPersonen
    FdWsAusbildungenExpFilter_FdiskIdPersonen,
    // *value: FdiskIdMitgliedschaften
    FdWsAusbildungenExpFilter_FdiskIdMitgliedschaften,
    // *value: FdiskIdAusbildungen
    FdWsAusbildungenExpFilter_FdiskIdAusbildungen
  };

  // *baseType: string
  // *renamed: true
  enum FdWsFunktionenExpFilter
  {
    // *value: FdiskIdFunktionen
    FdWsFunktionenExpFilter_FdiskIdFunktionen,
    // *value: Langbezeichnung
    FdWsFunktionenExpFilter_Langbezeichnung,
    // *value: Kurzbezeichnung
    FdWsFunktionenExpFilter_Kurzbezeichnung,
    // *value: LetzteAenderungVon
    FdWsFunktionenExpFilter_LetzteAenderungVon,
    // *value: LetzteAenderungBis
    FdWsFunktionenExpFilter_LetzteAenderungBis
  };

  // *baseType: string
  // *renamed: true
  enum FdWsFunktionaereExpFilter
  {
    // *value: FdiskIdFunktionen
    FdWsFunktionaereExpFilter_FdiskIdFunktionen,
    // *value: FdiskIdMitglieder
    FdWsFunktionaereExpFilter_FdiskIdMitglieder,
    // *value: InstanzNummer
    FdWsFunktionaereExpFilter_InstanzNummer,
    // *value: GueltigVonVon
    FdWsFunktionaereExpFilter_GueltigVonVon,
    // *value: GueltigVonBis
    FdWsFunktionaereExpFilter_GueltigVonBis,
    // *value: GueltigBisVon
    FdWsFunktionaereExpFilter_GueltigBisVon,
    // *value: GueltigBisBis
    FdWsFunktionaereExpFilter_GueltigBisBis,
    // *value: NurAktive
    FdWsFunktionaereExpFilter_NurAktive,
    // *value: LetzteAenderungVon
    FdWsFunktionaereExpFilter_LetzteAenderungVon,
    // *value: LetzteAenderungBis
    FdWsFunktionaereExpFilter_LetzteAenderungBis,
    // *value: DienstgradKurzBezeichnung
    FdWsFunktionaereExpFilter_DienstgradKurzBezeichnung,
    // *value: FunktionenKurzBezeichnung
    FdWsFunktionaereExpFilter_FunktionenKurzBezeichnung,
    // *value: FdiskIdPersonen
    FdWsFunktionaereExpFilter_FdiskIdPersonen
  };

  // *baseType: string
  // *renamed: true
  enum FdWsInstanzenExpFilter
  {
    // *value: FdiskIdInstanzen
    FdWsInstanzenExpFilter_FdiskIdInstanzen,
    // *value: Instanznummer
    FdWsInstanzenExpFilter_Instanznummer,
    // *value: InstanzArt
    FdWsInstanzenExpFilter_InstanzArt,
    // *value: InstanzTyp
    FdWsInstanzenExpFilter_InstanzTyp
  };

  // *baseType: string
  // *renamed: true
  enum FdWsFeuerwachenExpFilter
  {
    // *value: FdiskIdInstanzen
    FdWsFeuerwachenExpFilter_FdiskIdInstanzen,
    // *value: Instanznummer
    FdWsFeuerwachenExpFilter_Instanznummer
  };

  // *baseType: string
  // *renamed: true
  enum FdWsSonderdiensteExpFilter
  {
    // *value: FdiskIdInstanzen
    FdWsSonderdiensteExpFilter_FdiskIdInstanzen,
    // *value: Instanznummer
    FdWsSonderdiensteExpFilter_Instanznummer,
    // *value: InstanzArt
    FdWsSonderdiensteExpFilter_InstanzArt,
    // *value: InstanzTyp
    FdWsSonderdiensteExpFilter_InstanzTyp
  };

  // *baseType: string
  // *renamed: true
  enum FdWsFWInstanzen144ExpFilter
  {
    // *value: FdiskIdInstanzen
    FdWsFWInstanzen144ExpFilter_FdiskIdInstanzen,
    // *value: Instanznummer
    FdWsFWInstanzen144ExpFilter_Instanznummer,
    // *value: InstanzArt
    FdWsFWInstanzen144ExpFilter_InstanzArt
  };

  // *baseType: string
  // *renamed: true
  enum FdWsGeraeteExpFilter
  {
    // *value: InstanzNummer
    FdWsGeraeteExpFilter_InstanzNummer,
    // *value: FdiskIdInstanzen
    FdWsGeraeteExpFilter_FdiskIdInstanzen,
    // *value: FdiskIdGeraete
    FdWsGeraeteExpFilter_FdiskIdGeraete,
    // *value: GeraeteGruppe
    FdWsGeraeteExpFilter_GeraeteGruppe,
    // *value: GeraeteStandard
    FdWsGeraeteExpFilter_GeraeteStandard,
    // *value: GeraeteStatus
    FdWsGeraeteExpFilter_GeraeteStatus,
    // *value: LetzteAenderungVon
    FdWsGeraeteExpFilter_LetzteAenderungVon,
    // *value: LetzteAenderungBis
    FdWsGeraeteExpFilter_LetzteAenderungBis
  };

  // *baseType: string
  // *renamed: true
  enum FdWsFahrzeugeExpFilter
  {
    // *value: InstanzNummer
    FdWsFahrzeugeExpFilter_InstanzNummer,
    // *value: FdiskIdInstanzen
    FdWsFahrzeugeExpFilter_FdiskIdInstanzen,
    // *value: FzgStatus
    FdWsFahrzeugeExpFilter_FzgStatus,
    // *value: TaktischeBezeichnung
    FdWsFahrzeugeExpFilter_TaktischeBezeichnung,
    // *value: Feuerwache
    FdWsFahrzeugeExpFilter_Feuerwache,
    // *value: FdiskIdFahrzeuge
    FdWsFahrzeugeExpFilter_FdiskIdFahrzeuge,
    // *value: LetzteAenderungVon
    FdWsFahrzeugeExpFilter_LetzteAenderungVon,
    // *value: LetzteAenderungBis
    FdWsFahrzeugeExpFilter_LetzteAenderungBis
  };

  // *baseType: string
  // *renamed: true
  enum FdWsErreichbarkeitenFeuerwehrhaeuserExpFilter
  {
    // *value: FdiskIdFeuerwehrhaeuser
    FdWsErreichbarkeitenFeuerwehrhaeuserExpFilter_FdiskIdFeuerwehrhaeuser,
    // *value: Feuerwache
    FdWsErreichbarkeitenFeuerwehrhaeuserExpFilter_Feuerwache,
    // *value: InstanzNummer
    FdWsErreichbarkeitenFeuerwehrhaeuserExpFilter_InstanzNummer,
    // *value: InstanzArt
    FdWsErreichbarkeitenFeuerwehrhaeuserExpFilter_InstanzArt,
    // *value: ErreichbarkeitArt
    FdWsErreichbarkeitenFeuerwehrhaeuserExpFilter_ErreichbarkeitArt,
    // *value: LetzteAenderungVon
    FdWsErreichbarkeitenFeuerwehrhaeuserExpFilter_LetzteAenderungVon,
    // *value: LetzteAenderungBis
    FdWsErreichbarkeitenFeuerwehrhaeuserExpFilter_LetzteAenderungBis
  };

  // *baseType: string
  // *renamed: true
  enum FdWsErreichbarkeitenPersonenExpFilter
  {
    // *value: FdiskIdPersonen
    FdWsErreichbarkeitenPersonenExpFilter_FdiskIdPersonen,
    // *value: ErreichbarkeitArt
    FdWsErreichbarkeitenPersonenExpFilter_ErreichbarkeitArt,
    // *value: LetzteAenderungVon
    FdWsErreichbarkeitenPersonenExpFilter_LetzteAenderungVon,
    // *value: LetzteAenderungBis
    FdWsErreichbarkeitenPersonenExpFilter_LetzteAenderungBis
  };

  // *baseType: string
  // *renamed: true
  enum FdWsFeuerwehrhaeuserExpFilter
  {
    // *value: FdiskIdFeuerwehrhaeuser
    FdWsFeuerwehrhaeuserExpFilter_FdiskIdFeuerwehrhaeuser,
    // *value: FdiskIdFeuerwehren
    FdWsFeuerwehrhaeuserExpFilter_FdiskIdFeuerwehren,
    // *value: FdiskIdInstanzen
    FdWsFeuerwehrhaeuserExpFilter_FdiskIdInstanzen,
    // *value: Instanznummer
    FdWsFeuerwehrhaeuserExpFilter_Instanznummer,
    // *value: LetzteAenderungVon
    FdWsFeuerwehrhaeuserExpFilter_LetzteAenderungVon,
    // *value: LetzteAenderungBis
    FdWsFeuerwehrhaeuserExpFilter_LetzteAenderungBis,
    // *value: Feuerwache
    FdWsFeuerwehrhaeuserExpFilter_Feuerwache
  };

  // *baseType: string
  // *renamed: true
  enum FdWsFeuerwehrGemeindenExpFilter
  {
    // *value: FdiskIdFwInstanzen
    FdWsFeuerwehrGemeindenExpFilter_FdiskIdFwInstanzen,
    // *value: FwNummer
    FdWsFeuerwehrGemeindenExpFilter_FwNummer,
    // *value: FwName
    FdWsFeuerwehrGemeindenExpFilter_FwName,
    // *value: FdiskIdGemInstanzen
    FdWsFeuerwehrGemeindenExpFilter_FdiskIdGemInstanzen,
    // *value: GemNummer
    FdWsFeuerwehrGemeindenExpFilter_GemNummer,
    // *value: GemName
    FdWsFeuerwehrGemeindenExpFilter_GemName
  };

  // *baseType: string
  // *renamed: true
  enum FdWsWasserdienstleistungsbewerbeExpFilter
  {
    // *value: FdiskIdBewerbe
    FdWsWasserdienstleistungsbewerbeExpFilter_FdiskIdBewerbe
  };

  // *baseType: string
  // *renamed: true
  enum FdWsFeuerwehrleistungsbewerbeExpFilter
  {
    // *value: FdiskIdBewerbe
    FdWsFeuerwehrleistungsbewerbeExpFilter_FdiskIdBewerbe
  };

  // *baseType: string
  // *renamed: true
  enum StatusCodes
  {
    // *value: OK
    StatusCodes_OK,
    // *value: UNKNOWN_ERROR
    StatusCodes_UNKNOWN_ERROR,
    // *value: NO_DATA_FOUND
    StatusCodes_NO_DATA_FOUND,
    // *value: NO_MORE_DATA
    StatusCodes_NO_MORE_DATA,
    // *value: MISSING_DATA
    StatusCodes_MISSING_DATA,
    // *value: LOGIN_FAILED
    StatusCodes_LOGIN_FAILED,
    // *value: NO_PERMISSION
    StatusCodes_NO_PERMISSION,
    // *value: NOT_LOGGED_IN
    StatusCodes_NOT_LOGGED_IN,
    // *value: MIN_IDENTIFIER_NOT_SET
    StatusCodes_MIN_IDENTIFIER_NOT_SET,
    // *value: IDENTIFIER_NOT_UNIQUE
    StatusCodes_IDENTIFIER_NOT_UNIQUE,
    // *value: NO_IMPORT_DATA
    StatusCodes_NO_IMPORT_DATA
  };

  struct FdWsPrepareDataRequest
  {
    ::FdWsExportType type;
    staff::Optional< ::FdWsKurseRequest > kurse;
    staff::Optional< ::FdWsMitgliederRequest > mitglieder;
    staff::Optional< ::FdWsFWMitglieder144Request > fwMitglieder144;
    staff::Optional< ::FdWsDienstgradeRequest > dienstgrade;
    staff::Optional< ::FdWsAusbildungenRequest > ausbildungen;
    staff::Optional< ::FdWsFunktionenRequest > funktionen;
    staff::Optional< ::FdWsFunktionaereRequest > funktionaere;
    staff::Optional< ::FdWsInstanzenRequest > instanzen;
    staff::Optional< ::FdWsFeuerwachenRequest > feuerwachen;
    staff::Optional< ::FdWsSonderdiensteRequest > sonderdienste;
    staff::Optional< ::FdWsFWInstanzen144Request > fwInstanzen144;
    staff::Optional< ::FdWsGeraeteRequest > geraete;
    staff::Optional< ::FdWsFahrzeugeRequest > fahrzeuge;
    staff::Optional< ::FdWsErreichbarkeitenFeuerwehrhaeuserRequest > erreichbarkeitenfeuerwehrhaeuser;
    staff::Optional< ::FdWsErreichbarkeitenPersonenRequest > erreichbarkeitenpersonen;
    staff::Optional< ::FdWsFeuerwehrhaeuserRequest > feuerwehrhaeuser;
    staff::Optional< ::FdWsFeuerwehrGemeindenRequest > feuerwehrgemeinden;
    staff::Optional< ::FdWsWasserdienstleistungsbewerbeRequest > wasserdienstleistungsbewerbe;
    staff::Optional< ::FdWsFeuerwehrleistungsbewerbeRequest > feuerwehrleistungsbewerbe;
  };

  struct FdWsKurseRequest
  {
    staff::Optional< ::ArrayOfArrayOfFdWsKurseRequestFilter > filterGroup;
  };

  struct ArrayOfArrayOfFdWsKurseRequestFilter
  {
    // *itemName: ArrayOfFdWsKurseRequestFilter
    // *useParentElement: true
    std::list< staff::Nillable< ::ArrayOfFdWsKurseRequestFilter > > ArrayOfFdWsKurseRequestFilter;
  };

  struct ArrayOfFdWsKurseRequestFilter
  {
    // *itemName: FdWsKurseRequestFilter
    // *useParentElement: true
    std::list< staff::Nillable< ::FdWsKurseRequestFilter > > FdWsKurseRequestFilter;
  };

  struct FdWsKurseRequestFilter
  {
    ::FdWsKurseExpFilter type;
    staff::Optional<std::string> value;
  };

  struct FdWsMitgliederRequest
  {
    staff::Optional< ::ArrayOfArrayOfFdWsMitgliederRequestFilter > filterGroup;
  };

  struct ArrayOfArrayOfFdWsMitgliederRequestFilter
  {
    // *itemName: ArrayOfFdWsMitgliederRequestFilter
    // *useParentElement: true
    std::list< staff::Nillable< ::ArrayOfFdWsMitgliederRequestFilter > > ArrayOfFdWsMitgliederRequestFilter;
  };

  struct ArrayOfFdWsMitgliederRequestFilter
  {
    // *itemName: FdWsMitgliederRequestFilter
    // *useParentElement: true
    std::list< staff::Nillable< ::FdWsMitgliederRequestFilter > > FdWsMitgliederRequestFilter;
  };

  struct FdWsMitgliederRequestFilter
  {
    ::FdWsMitgliederExpFilter type;
    staff::Optional<std::string> value;
  };

  struct FdWsFWMitglieder144Request
  {
    staff::Optional< ::ArrayOfArrayOfFdWsFWMitglieder144RequestFilter > filterGroup;
  };

  struct ArrayOfArrayOfFdWsFWMitglieder144RequestFilter
  {
    // *itemName: ArrayOfFdWsFWMitglieder144RequestFilter
    // *useParentElement: true
    std::list< staff::Nillable< ::ArrayOfFdWsFWMitglieder144RequestFilter > > ArrayOfFdWsFWMitglieder144RequestFilter;
  };

  struct ArrayOfFdWsFWMitglieder144RequestFilter
  {
    // *itemName: FdWsFWMitglieder144RequestFilter
    // *useParentElement: true
    std::list< staff::Nillable< ::FdWsFWMitglieder144RequestFilter > > FdWsFWMitglieder144RequestFilter;
  };

  struct FdWsFWMitglieder144RequestFilter
  {
    ::FdWsFWMitglieder144ExpFilter type;
    staff::Optional<std::string> value;
  };

  struct FdWsDienstgradeRequest
  {
    staff::Optional< ::ArrayOfArrayOfFdWsDienstgradeRequestFilter > filterGroup;
  };

  struct ArrayOfArrayOfFdWsDienstgradeRequestFilter
  {
    // *itemName: ArrayOfFdWsDienstgradeRequestFilter
    // *useParentElement: true
    std::list< staff::Nillable< ::ArrayOfFdWsDienstgradeRequestFilter > > ArrayOfFdWsDienstgradeRequestFilter;
  };

  struct ArrayOfFdWsDienstgradeRequestFilter
  {
    // *itemName: FdWsDienstgradeRequestFilter
    // *useParentElement: true
    std::list< staff::Nillable< ::FdWsDienstgradeRequestFilter > > FdWsDienstgradeRequestFilter;
  };

  struct FdWsDienstgradeRequestFilter
  {
    ::FdWsDienstgradeExpFilter type;
    staff::Optional<std::string> value;
  };

  struct FdWsAusbildungenRequest
  {
    staff::Optional< ::ArrayOfArrayOfFdWsAusbildungenRequestFilter > filterGroup;
  };

  struct ArrayOfArrayOfFdWsAusbildungenRequestFilter
  {
    // *itemName: ArrayOfFdWsAusbildungenRequestFilter
    // *useParentElement: true
    std::list< staff::Nillable< ::ArrayOfFdWsAusbildungenRequestFilter > > ArrayOfFdWsAusbildungenRequestFilter;
  };

  struct ArrayOfFdWsAusbildungenRequestFilter
  {
    // *itemName: FdWsAusbildungenRequestFilter
    // *useParentElement: true
    std::list< staff::Nillable< ::FdWsAusbildungenRequestFilter > > FdWsAusbildungenRequestFilter;
  };

  struct FdWsAusbildungenRequestFilter
  {
    ::FdWsAusbildungenExpFilter type;
    staff::Optional<std::string> value;
  };

  struct FdWsFunktionenRequest
  {
    staff::Optional< ::ArrayOfArrayOfFdWsFunktionenRequestFilter > filterGroup;
  };

  struct ArrayOfArrayOfFdWsFunktionenRequestFilter
  {
    // *itemName: ArrayOfFdWsFunktionenRequestFilter
    // *useParentElement: true
    std::list< staff::Nillable< ::ArrayOfFdWsFunktionenRequestFilter > > ArrayOfFdWsFunktionenRequestFilter;
  };

  struct ArrayOfFdWsFunktionenRequestFilter
  {
    // *itemName: FdWsFunktionenRequestFilter
    // *useParentElement: true
    std::list< staff::Nillable< ::FdWsFunktionenRequestFilter > > FdWsFunktionenRequestFilter;
  };

  struct FdWsFunktionenRequestFilter
  {
    ::FdWsFunktionenExpFilter type;
    staff::Optional<std::string> value;
  };

  struct FdWsFunktionaereRequest
  {
    staff::Optional< ::ArrayOfArrayOfFdWsFunktionaereRequestFilter > filterGroup;
  };

  struct ArrayOfArrayOfFdWsFunktionaereRequestFilter
  {
    // *itemName: ArrayOfFdWsFunktionaereRequestFilter
    // *useParentElement: true
    std::list< staff::Nillable< ::ArrayOfFdWsFunktionaereRequestFilter > > ArrayOfFdWsFunktionaereRequestFilter;
  };

  struct ArrayOfFdWsFunktionaereRequestFilter
  {
    // *itemName: FdWsFunktionaereRequestFilter
    // *useParentElement: true
    std::list< staff::Nillable< ::FdWsFunktionaereRequestFilter > > FdWsFunktionaereRequestFilter;
  };

  struct FdWsFunktionaereRequestFilter
  {
    ::FdWsFunktionaereExpFilter type;
    staff::Optional<std::string> value;
  };

  struct FdWsInstanzenRequest
  {
    staff::Optional< ::ArrayOfArrayOfFdWsInstanzenRequestFilter > filterGroup;
  };

  struct ArrayOfArrayOfFdWsInstanzenRequestFilter
  {
    // *itemName: ArrayOfFdWsInstanzenRequestFilter
    // *useParentElement: true
    std::list< staff::Nillable< ::ArrayOfFdWsInstanzenRequestFilter > > ArrayOfFdWsInstanzenRequestFilter;
  };

  struct ArrayOfFdWsInstanzenRequestFilter
  {
    // *itemName: FdWsInstanzenRequestFilter
    // *useParentElement: true
    std::list< staff::Nillable< ::FdWsInstanzenRequestFilter > > FdWsInstanzenRequestFilter;
  };

  struct FdWsInstanzenRequestFilter
  {
    ::FdWsInstanzenExpFilter type;
    staff::Optional<std::string> value;
  };

  struct FdWsFeuerwachenRequest
  {
    staff::Optional< ::ArrayOfArrayOfFdWsFeuerwachenRequestFilter > filterGroup;
  };

  struct ArrayOfArrayOfFdWsFeuerwachenRequestFilter
  {
    // *itemName: ArrayOfFdWsFeuerwachenRequestFilter
    // *useParentElement: true
    std::list< staff::Nillable< ::ArrayOfFdWsFeuerwachenRequestFilter > > ArrayOfFdWsFeuerwachenRequestFilter;
  };

  struct ArrayOfFdWsFeuerwachenRequestFilter
  {
    // *itemName: FdWsFeuerwachenRequestFilter
    // *useParentElement: true
    std::list< staff::Nillable< ::FdWsFeuerwachenRequestFilter > > FdWsFeuerwachenRequestFilter;
  };

  struct FdWsFeuerwachenRequestFilter
  {
    ::FdWsFeuerwachenExpFilter type;
    staff::Optional<std::string> value;
  };

  struct FdWsSonderdiensteRequest
  {
    staff::Optional< ::ArrayOfArrayOfFdWsSonderdiensteRequestFilter > filterGroup;
  };

  struct ArrayOfArrayOfFdWsSonderdiensteRequestFilter
  {
    // *itemName: ArrayOfFdWsSonderdiensteRequestFilter
    // *useParentElement: true
    std::list< staff::Nillable< ::ArrayOfFdWsSonderdiensteRequestFilter > > ArrayOfFdWsSonderdiensteRequestFilter;
  };

  struct ArrayOfFdWsSonderdiensteRequestFilter
  {
    // *itemName: FdWsSonderdiensteRequestFilter
    // *useParentElement: true
    std::list< staff::Nillable< ::FdWsSonderdiensteRequestFilter > > FdWsSonderdiensteRequestFilter;
  };

  struct FdWsSonderdiensteRequestFilter
  {
    ::FdWsSonderdiensteExpFilter type;
    staff::Optional<std::string> value;
  };

  struct FdWsFWInstanzen144Request
  {
    staff::Optional< ::ArrayOfArrayOfFdWsFWInstanzen144RequestFilter > filterGroup;
  };

  struct ArrayOfArrayOfFdWsFWInstanzen144RequestFilter
  {
    // *itemName: ArrayOfFdWsFWInstanzen144RequestFilter
    // *useParentElement: true
    std::list< staff::Nillable< ::ArrayOfFdWsFWInstanzen144RequestFilter > > ArrayOfFdWsFWInstanzen144RequestFilter;
  };

  struct ArrayOfFdWsFWInstanzen144RequestFilter
  {
    // *itemName: FdWsFWInstanzen144RequestFilter
    // *useParentElement: true
    std::list< staff::Nillable< ::FdWsFWInstanzen144RequestFilter > > FdWsFWInstanzen144RequestFilter;
  };

  struct FdWsFWInstanzen144RequestFilter
  {
    ::FdWsFWInstanzen144ExpFilter type;
    staff::Optional<std::string> value;
  };

  struct FdWsGeraeteRequest
  {
    staff::Optional< ::ArrayOfArrayOfFdWsGeraeteRequestFilter > filterGroup;
  };

  struct ArrayOfArrayOfFdWsGeraeteRequestFilter
  {
    // *itemName: ArrayOfFdWsGeraeteRequestFilter
    // *useParentElement: true
    std::list< staff::Nillable< ::ArrayOfFdWsGeraeteRequestFilter > > ArrayOfFdWsGeraeteRequestFilter;
  };

  struct ArrayOfFdWsGeraeteRequestFilter
  {
    // *itemName: FdWsGeraeteRequestFilter
    // *useParentElement: true
    std::list< staff::Nillable< ::FdWsGeraeteRequestFilter > > FdWsGeraeteRequestFilter;
  };

  struct FdWsGeraeteRequestFilter
  {
    ::FdWsGeraeteExpFilter type;
    staff::Optional<std::string> value;
  };

  struct FdWsFahrzeugeRequest
  {
    staff::Optional< ::ArrayOfArrayOfFdWsFahrzeugeRequestFilter > filterGroup;
  };

  struct ArrayOfArrayOfFdWsFahrzeugeRequestFilter
  {
    // *itemName: ArrayOfFdWsFahrzeugeRequestFilter
    // *useParentElement: true
    std::list< staff::Nillable< ::ArrayOfFdWsFahrzeugeRequestFilter > > ArrayOfFdWsFahrzeugeRequestFilter;
  };

  struct ArrayOfFdWsFahrzeugeRequestFilter
  {
    // *itemName: FdWsFahrzeugeRequestFilter
    // *useParentElement: true
    std::list< staff::Nillable< ::FdWsFahrzeugeRequestFilter > > FdWsFahrzeugeRequestFilter;
  };

  struct FdWsFahrzeugeRequestFilter
  {
    ::FdWsFahrzeugeExpFilter type;
    staff::Optional<std::string> value;
  };

  struct FdWsErreichbarkeitenFeuerwehrhaeuserRequest
  {
    staff::Optional< ::ArrayOfArrayOfFdWsErreichbarkeitenFeuerwehrhaeuserRequestFilter > filterGroup;
  };

  struct ArrayOfArrayOfFdWsErreichbarkeitenFeuerwehrhaeuserRequestFilter
  {
    // *itemName: ArrayOfFdWsErreichbarkeitenFeuerwehrhaeuserRequestFilter
    // *useParentElement: true
    std::list< staff::Nillable< ::ArrayOfFdWsErreichbarkeitenFeuerwehrhaeuserRequestFilter > > ArrayOfFdWsErreichbarkeitenFeuerwehrhaeuserRequestFilter;
  };

  struct ArrayOfFdWsErreichbarkeitenFeuerwehrhaeuserRequestFilter
  {
    // *itemName: FdWsErreichbarkeitenFeuerwehrhaeuserRequestFilter
    // *useParentElement: true
    std::list< staff::Nillable< ::FdWsErreichbarkeitenFeuerwehrhaeuserRequestFilter > > FdWsErreichbarkeitenFeuerwehrhaeuserRequestFilter;
  };

  struct FdWsErreichbarkeitenFeuerwehrhaeuserRequestFilter
  {
    ::FdWsErreichbarkeitenFeuerwehrhaeuserExpFilter type;
    staff::Optional<std::string> value;
  };

  struct FdWsErreichbarkeitenPersonenRequest
  {
    staff::Optional< ::ArrayOfArrayOfFdWsErreichbarkeitenPersonenRequestFilter > filterGroup;
  };

  struct ArrayOfArrayOfFdWsErreichbarkeitenPersonenRequestFilter
  {
    // *itemName: ArrayOfFdWsErreichbarkeitenPersonenRequestFilter
    // *useParentElement: true
    std::list< staff::Nillable< ::ArrayOfFdWsErreichbarkeitenPersonenRequestFilter > > ArrayOfFdWsErreichbarkeitenPersonenRequestFilter;
  };

  struct ArrayOfFdWsErreichbarkeitenPersonenRequestFilter
  {
    // *itemName: FdWsErreichbarkeitenPersonenRequestFilter
    // *useParentElement: true
    std::list< staff::Nillable< ::FdWsErreichbarkeitenPersonenRequestFilter > > FdWsErreichbarkeitenPersonenRequestFilter;
  };

  struct FdWsErreichbarkeitenPersonenRequestFilter
  {
    ::FdWsErreichbarkeitenPersonenExpFilter type;
    staff::Optional<std::string> value;
  };

  struct FdWsFeuerwehrhaeuserRequest
  {
    staff::Optional< ::ArrayOfArrayOfFdWsFeuerwehrhaeuserRequestFilter > filterGroup;
  };

  struct ArrayOfArrayOfFdWsFeuerwehrhaeuserRequestFilter
  {
    // *itemName: ArrayOfFdWsFeuerwehrhaeuserRequestFilter
    // *useParentElement: true
    std::list< staff::Nillable< ::ArrayOfFdWsFeuerwehrhaeuserRequestFilter > > ArrayOfFdWsFeuerwehrhaeuserRequestFilter;
  };

  struct ArrayOfFdWsFeuerwehrhaeuserRequestFilter
  {
    // *itemName: FdWsFeuerwehrhaeuserRequestFilter
    // *useParentElement: true
    std::list< staff::Nillable< ::FdWsFeuerwehrhaeuserRequestFilter > > FdWsFeuerwehrhaeuserRequestFilter;
  };

  struct FdWsFeuerwehrhaeuserRequestFilter
  {
    ::FdWsFeuerwehrhaeuserExpFilter type;
    staff::Optional<std::string> value;
  };

  struct FdWsFeuerwehrGemeindenRequest
  {
    staff::Optional< ::ArrayOfArrayOfFdWsFeuerwehrGemeindenRequestFilter > filterGroup;
  };

  struct ArrayOfArrayOfFdWsFeuerwehrGemeindenRequestFilter
  {
    // *itemName: ArrayOfFdWsFeuerwehrGemeindenRequestFilter
    // *useParentElement: true
    std::list< staff::Nillable< ::ArrayOfFdWsFeuerwehrGemeindenRequestFilter > > ArrayOfFdWsFeuerwehrGemeindenRequestFilter;
  };

  struct ArrayOfFdWsFeuerwehrGemeindenRequestFilter
  {
    // *itemName: FdWsFeuerwehrGemeindenRequestFilter
    // *useParentElement: true
    std::list< staff::Nillable< ::FdWsFeuerwehrGemeindenRequestFilter > > FdWsFeuerwehrGemeindenRequestFilter;
  };

  struct FdWsFeuerwehrGemeindenRequestFilter
  {
    ::FdWsFeuerwehrGemeindenExpFilter type;
    staff::Optional<std::string> value;
  };

  struct FdWsWasserdienstleistungsbewerbeRequest
  {
    staff::Optional< ::ArrayOfArrayOfFdWsWasserdienstleistungsbewerbeRequestFilter > filterGroup;
  };

  struct ArrayOfArrayOfFdWsWasserdienstleistungsbewerbeRequestFilter
  {
    // *itemName: ArrayOfFdWsWasserdienstleistungsbewerbeRequestFilter
    // *useParentElement: true
    std::list< staff::Nillable< ::ArrayOfFdWsWasserdienstleistungsbewerbeRequestFilter > > ArrayOfFdWsWasserdienstleistungsbewerbeRequestFilter;
  };

  struct ArrayOfFdWsWasserdienstleistungsbewerbeRequestFilter
  {
    // *itemName: FdWsWasserdienstleistungsbewerbeRequestFilter
    // *useParentElement: true
    std::list< staff::Nillable< ::FdWsWasserdienstleistungsbewerbeRequestFilter > > FdWsWasserdienstleistungsbewerbeRequestFilter;
  };

  struct FdWsWasserdienstleistungsbewerbeRequestFilter
  {
    ::FdWsWasserdienstleistungsbewerbeExpFilter type;
    staff::Optional<std::string> value;
  };

  struct FdWsFeuerwehrleistungsbewerbeRequest
  {
    staff::Optional< ::ArrayOfArrayOfFdWsFeuerwehrleistungsbewerbeRequestFilter > filterGroup;
  };

  struct ArrayOfArrayOfFdWsFeuerwehrleistungsbewerbeRequestFilter
  {
    // *itemName: ArrayOfFdWsFeuerwehrleistungsbewerbeRequestFilter
    // *useParentElement: true
    std::list< staff::Nillable< ::ArrayOfFdWsFeuerwehrleistungsbewerbeRequestFilter > > ArrayOfFdWsFeuerwehrleistungsbewerbeRequestFilter;
  };

  struct ArrayOfFdWsFeuerwehrleistungsbewerbeRequestFilter
  {
    // *itemName: FdWsFeuerwehrleistungsbewerbeRequestFilter
    // *useParentElement: true
    std::list< staff::Nillable< ::FdWsFeuerwehrleistungsbewerbeRequestFilter > > FdWsFeuerwehrleistungsbewerbeRequestFilter;
  };

  struct FdWsFeuerwehrleistungsbewerbeRequestFilter
  {
    ::FdWsFeuerwehrleistungsbewerbeExpFilter type;
    staff::Optional<std::string> value;
  };

  struct FdWsPrepareDataReturn
  {
    long resultCount;
    staff::Optional<std::string> statusMessage;
    ::StatusCodes statusCode;
  };

  struct FdWsGetNextDataBlockReturn
  {
    staff::Optional<std::string> statusMessage;
    ::StatusCodes statusCode;
    staff::Optional< ::ArrayOfFdWsFWMitglieder144Struct > fwMitglieder144;
    staff::Optional< ::ArrayOfFdWsMitgliederStruct > mitglieder;
    staff::Optional< ::ArrayOfFdWsAusbildungenStruct > ausbildungen;
    staff::Optional< ::ArrayOfFdWsKurseStruct > kurse;
    staff::Optional< ::ArrayOfFdWsDienstgradeStruct > dienstgrade;
    staff::Optional< ::ArrayOfFdWsSonderdiensteStruct > sonderdienste;
    staff::Optional< ::ArrayOfFdWsFunktionenStruct > funktionen;
    staff::Optional< ::ArrayOfFdWsFunktionaereStruct > funktionaere;
    staff::Optional< ::ArrayOfFdWsInstanzenStruct > instanzen;
    staff::Optional< ::ArrayOfFdWsFWInstanzen144Struct > fwInstanzen144;
    staff::Optional< ::ArrayOfFdWsGeraeteStruct > geraete;
    staff::Optional< ::ArrayOfFdWsFahrzeugeStruct > fahrzeuge;
    staff::Optional< ::ArrayOfFdWsFeuerwachenStruct > feuerwachen;
    staff::Optional< ::ArrayOfFdWsErreichbarkeitenFeuerwehrhaeuserStruct > erreichbarkeitenfeuerwehrhaeuser;
    staff::Optional< ::ArrayOfFdWsErreichbarkeitenPersonenStruct > erreichbarkeitenpersonen;
    staff::Optional< ::ArrayOfFdWsFeuerwehrhaeuserStruct > feuerwehrhaeuser;
    staff::Optional< ::ArrayOfFdWsFeuerwehrGemeindenStruct > feuerwehrgemeinden;
    staff::Optional< ::ArrayOfFdWsWasserdienstleistungsbewerbeStruct > wasserdienstleistungsbewerbe;
    staff::Optional< ::ArrayOfFdWsFeuerwehrleistungsbewerbeStruct > feuerwehrleistungsbewerbe;
  };

  struct ArrayOfFdWsFWMitglieder144Struct
  {
    // *itemName: FdWsFWMitglieder144Struct
    // *useParentElement: true
    std::list< staff::Nillable< ::FdWsFWMitglieder144Struct > > FdWsFWMitglieder144Struct;
  };

  struct TypeMapper
  {
  };

  struct Writer: public ::TypeMapper
  {
  };

  struct FdWsFWMitglieder144Struct: public ::Writer
  {
    long FdiskIdInstanzen;
    staff::Optional<std::string> Instanznummer;
    staff::Optional<std::string> Standesbuchnummer;
    staff::Optional<std::string> Vorname;
    staff::Optional<std::string> Zuname;
    long FdiskIdMitglieder;
    long FdiskIdPersonen;
    staff::Optional<std::string> Titel;
    staff::Optional<std::string> Namenszusatz;
  };

  struct ArrayOfFdWsMitgliederStruct
  {
    // *itemName: FdWsMitgliederStruct
    // *useParentElement: true
    std::list< staff::Nillable< ::FdWsMitgliederStruct > > FdWsMitgliederStruct;
  };

  struct FdWsMitgliederStruct: public ::Writer
  {
    long FdiskIdMitglieder;
    long FdiskIdPersonen;
    long FdiskIdDienstgrade;
    staff::Optional<std::string> Instanznummer;
    staff::Optional<std::string> Standesbuchnummer;
    staff::Optional<std::string> Dienstgrad;
    staff::Optional<std::string> DienstgradLang;
    staff::Optional<std::string> Titel;
    staff::Optional<std::string> Vorname;
    staff::Optional<std::string> Zuname;
    staff::Optional<std::string> Namenszusatz;
    staff::Optional<std::string> Strasse;
    staff::Optional<std::string> Nummer;
    staff::Optional<std::string> Stiege;
    staff::Optional<std::string> Kathastralgemeinde;
    staff::Optional<std::string> PLZ;
    staff::Optional<std::string> Ort;
    staff::Optional<std::string> Geschlecht;
    staff::Optional<std::string> ErreichbarkeitMail;
    staff::Optional<std::string> ErreichbarkeitMobil;
    staff::Optional<std::string> ErreichbarkeitFestnetz;
    staff::Optional<std::string> ErreichbarkeitFax;
    staff::Optional<std::string> ErreichbarkeitGruppenRic;
    staff::Optional<std::string> ErreichbarkeitUrl;
    staff::dateTime Geburtsdatum;
    staff::Optional<std::string> Versicherungsnummer;
    staff::dateTime DatumAbmeldung;
    staff::dateTime DatumEhrenmitglied;
    staff::dateTime DatumJugend;
    staff::dateTime DatumReserve;
    staff::dateTime DatumAktiv;
    staff::dateTime DatumEintritt;
    bool FlagAktiv;
    bool FlagEhrenmitglied;
    bool FlagJugend;
    bool FlagAbgemeldet;
    bool FlagReserve;
    bool FlagZivildienst;
    staff::dateTime LetzteAenderung;
    staff::Optional<std::string> ErreichbarkeitMobilFirma;
    staff::Optional<std::string> ErreichbarkeitFestnetzFirma;
    staff::Optional<std::string> Firma;
    staff::Optional<std::string> Branche;
    staff::Optional<std::string> FirmaStrasse;
    staff::Optional<std::string> FirmaNummer;
    staff::Optional<std::string> FirmaPlz;
    staff::Optional<std::string> FirmaOrt;
    staff::Optional<std::string> Fuehrerscheinklassen;
    staff::Optional<std::string> HasJugendfoerderung;
    bool Feuerwachen;
    long Vordienstzeiten;
  };

  struct ArrayOfFdWsAusbildungenStruct
  {
    // *itemName: FdWsAusbildungenStruct
    // *useParentElement: true
    std::list< staff::Nillable< ::FdWsAusbildungenStruct > > FdWsAusbildungenStruct;
  };

  struct FdWsAusbildungenStruct: public ::Writer
  {
    long FdiskIdAusbildungen;
    long FdiskIdErsatzlehrgaenge;
    staff::Optional<std::string> Bezeichnung;
    staff::Optional<std::string> Anmerkung;
    staff::dateTime Datum;
  };

  struct ArrayOfFdWsKurseStruct
  {
    // *itemName: FdWsKurseStruct
    // *useParentElement: true
    std::list< staff::Nillable< ::FdWsKurseStruct > > FdWsKurseStruct;
  };

  struct FdWsKurseStruct: public ::Writer
  {
    long FdiskIdKurse;
    staff::Optional<std::string> Kursnummer;
    staff::Optional<std::string> Bezeichnung;
    staff::Optional<std::string> Leistungsart;
    staff::dateTime Von;
    staff::dateTime Bis;
  };

  struct ArrayOfFdWsDienstgradeStruct
  {
    // *itemName: FdWsDienstgradeStruct
    // *useParentElement: true
    std::list< staff::Nillable< ::FdWsDienstgradeStruct > > FdWsDienstgradeStruct;
  };

  struct FdWsDienstgradeStruct: public ::Writer
  {
    long FdiskIdDienstgrade;
    staff::Optional<std::string> Langbezeichnung;
    staff::Optional<std::string> Kurzbezeichnung;
    long Rang;
    staff::dateTime LetzteAenderung;
  };

  struct ArrayOfFdWsSonderdiensteStruct
  {
    // *itemName: FdWsSonderdiensteStruct
    // *useParentElement: true
    std::list< staff::Nillable< ::FdWsSonderdiensteStruct > > FdWsSonderdiensteStruct;
  };

  struct FdWsSonderdiensteStruct: public ::Writer
  {
    long FdiskIdInstanzen;
    staff::dateTime Gruendungsdatum;
    staff::Optional<std::string> Instanznummer;
    staff::Optional<std::string> Instanzname;
    staff::Optional<std::string> InstanzArt;
    staff::Optional<std::string> InstanzTyp;
    staff::Optional<std::string> Strasse;
    staff::Optional<std::string> Nummer;
    staff::Optional<std::string> Stiege;
    staff::Optional<std::string> Kathastralgemeinde;
    staff::Optional<std::string> PLZ;
    staff::Optional<std::string> Ort;
    staff::Optional<std::string> ErreichbarkeitMail;
    staff::Optional<std::string> ErreichbarkeitMobil;
    staff::Optional<std::string> ErreichbarkeitFestnetz;
    staff::Optional<std::string> ErreichbarkeitFax;
    staff::Optional<std::string> ErreichbarkeitGruppenRic;
    staff::Optional<std::string> ErreichbarkeitUrl;
    staff::dateTime LetzteAenderung;
    staff::Optional<std::string> UAFKDONummer;
    staff::Optional<std::string> UAFKDOName;
    staff::Optional<std::string> UAFKDOInstanzartLang;
    staff::Optional<std::string> BFKDONummer;
    staff::Optional<std::string> BFKDOName;
    staff::Optional<std::string> BFKDOInstanzartLang;
    staff::Optional<std::string> AFKDONummer;
    staff::Optional<std::string> AFKDOName;
    staff::Optional<std::string> AFKDOInstanzartLang;
  };

  struct ArrayOfFdWsFunktionenStruct
  {
    // *itemName: FdWsFunktionenStruct
    // *useParentElement: true
    std::list< staff::Nillable< ::FdWsFunktionenStruct > > FdWsFunktionenStruct;
  };

  struct FdWsFunktionenStruct: public ::Writer
  {
    long FdiskIdFunktionen;
    staff::Optional<std::string> Langbezeichnung;
    staff::Optional<std::string> Kurzbezeichnung;
    staff::dateTime LetzteAenderung;
  };

  struct ArrayOfFdWsFunktionaereStruct
  {
    // *itemName: FdWsFunktionaereStruct
    // *useParentElement: true
    std::list< staff::Nillable< ::FdWsFunktionaereStruct > > FdWsFunktionaereStruct;
  };

  struct FdWsFunktionaereStruct: public ::Writer
  {
    long FdiskIdFunktionen;
    long FdiskIdMitglieder;
    staff::Optional<std::string> InstanzNummer;
    staff::Optional<std::string> Standesbuchnummer;
    staff::dateTime GueltigVon;
    staff::dateTime GueltigBis;
    staff::dateTime LetzteAenderung;
    staff::Optional<std::string> Vorname;
    staff::Optional<std::string> Zuname;
    staff::Optional<std::string> DienstgradKurzbezeichnung;
    staff::Optional<std::string> FunktionenKurzBezeichnung;
    staff::Optional<std::string> InstanzArt;
    long FdiskIdPersonen;
  };

  struct ArrayOfFdWsInstanzenStruct
  {
    // *itemName: FdWsInstanzenStruct
    // *useParentElement: true
    std::list< staff::Nillable< ::FdWsInstanzenStruct > > FdWsInstanzenStruct;
  };

  struct FdWsInstanzenStruct: public ::Writer
  {
    long FdiskIdInstanzen;
    staff::dateTime Gruendungsdatum;
    staff::Optional<std::string> Instanznummer;
    staff::Optional<std::string> Instanzname;
    staff::Optional<std::string> InstanzArt;
    staff::Optional<std::string> InstanzTyp;
    staff::Optional<std::string> Strasse;
    staff::Optional<std::string> Nummer;
    staff::Optional<std::string> Stiege;
    staff::Optional<std::string> Kathastralgemeinde;
    staff::Optional<std::string> PLZ;
    staff::Optional<std::string> Ort;
    staff::Optional<std::string> ErreichbarkeitMail;
    staff::Optional<std::string> ErreichbarkeitMobil;
    staff::Optional<std::string> ErreichbarkeitFestnetz;
    staff::Optional<std::string> ErreichbarkeitFax;
    staff::Optional<std::string> ErreichbarkeitGruppenRic;
    staff::Optional<std::string> ErreichbarkeitUrl;
    staff::dateTime LetzteAenderung;
    staff::Optional<std::string> UAFKDONummer;
    staff::Optional<std::string> UAFKDOName;
    staff::Optional<std::string> UAFKDOInstanzartLang;
    staff::Optional<std::string> BFKDONummer;
    staff::Optional<std::string> BFKDOName;
    staff::Optional<std::string> BFKDOInstanzartLang;
    staff::Optional<std::string> AFKDONummer;
    staff::Optional<std::string> AFKDOName;
    staff::Optional<std::string> AFKDOInstanzartLang;
    staff::Optional<std::string> GemeindeName;
    bool Feuerwachen;
    bool HatJugend;
  };

  struct ArrayOfFdWsFWInstanzen144Struct
  {
    // *itemName: FdWsFWInstanzen144Struct
    // *useParentElement: true
    std::list< staff::Nillable< ::FdWsFWInstanzen144Struct > > FdWsFWInstanzen144Struct;
  };

  struct FdWsFWInstanzen144Struct: public ::Writer
  {
    long FdiskIdInstanzen;
    staff::Optional<std::string> Instanznummer;
    staff::Optional<std::string> Instanzname;
    staff::Optional<std::string> InstanzArt;
    staff::Optional<std::string> InstanzArtLang;
  };

  struct ArrayOfFdWsGeraeteStruct
  {
    // *itemName: FdWsGeraeteStruct
    // *useParentElement: true
    std::list< staff::Nillable< ::FdWsGeraeteStruct > > FdWsGeraeteStruct;
  };

  struct FdWsGeraeteStruct: public ::Writer
  {
    long FdiskIdGeraete;
    long FdiskIdInstanzen;
    staff::Optional<std::string> InstanzNummer;
    staff::Optional<std::string> GeraeteBezeichnung;
    staff::Optional<std::string> GeraeteGruppe;
    staff::Optional<std::string> GeraeteStandard;
    long GeraeteAnzahl;
    staff::Optional<std::string> GeraeteStatus;
    staff::dateTime LetzteAenderung;
  };

  struct ArrayOfFdWsFahrzeugeStruct
  {
    // *itemName: FdWsFahrzeugeStruct
    // *useParentElement: true
    std::list< staff::Nillable< ::FdWsFahrzeugeStruct > > FdWsFahrzeugeStruct;
  };

  struct FdWsFahrzeugeStruct: public ::Writer
  {
    long FdiskIdFahrzeuge;
    long FdiskIdInstanzen;
    staff::Optional<std::string> InstanzNummer;
    staff::Optional<std::string> FzgStatus;
    staff::Optional<std::string> TaktischeBezeichnung;
    long Baujahr;
    staff::Optional<std::string> Feuerwache;
    staff::Optional<std::string> KfzKennzeichen;
    staff::Optional<std::string> Treibstoffart;
    staff::Optional<std::string> Funkrufzeichen;
    staff::Optional<std::string> Fahrzeugart;
    staff::Optional<std::string> Fahrzeugtyp;
    staff::Optional<std::string> Fahrzeugmarke;
    staff::Optional<std::string> Sonderausstattung;
    staff::dateTime LetzteAenderung;
  };

  struct ArrayOfFdWsFeuerwachenStruct
  {
    // *itemName: FdWsFeuerwachenStruct
    // *useParentElement: true
    std::list< staff::Nillable< ::FdWsFeuerwachenStruct > > FdWsFeuerwachenStruct;
  };

  struct FdWsFeuerwachenStruct: public ::Writer
  {
    long FdiskIdInstanzen;
    staff::dateTime Gruendungsdatum;
    staff::Optional<std::string> Instanznummer;
    staff::Optional<std::string> Instanzname;
    staff::Optional<std::string> Feuerwachenname;
    staff::Optional<std::string> Feuerwachennummer;
    staff::Optional<std::string> InstanzArt;
    staff::Optional<std::string> InstanzTyp;
    staff::Optional<std::string> Strasse;
    staff::Optional<std::string> Nummer;
    staff::Optional<std::string> Stiege;
    staff::Optional<std::string> Kathastralgemeinde;
    staff::Optional<std::string> PLZ;
    staff::Optional<std::string> Ort;
    staff::dateTime LetzteAenderung;
    staff::Optional<std::string> UAFKDONummer;
    staff::Optional<std::string> UAFKDOName;
    staff::Optional<std::string> UAFKDOInstanzartLang;
    staff::Optional<std::string> BFKDONummer;
    staff::Optional<std::string> BFKDOName;
    staff::Optional<std::string> BFKDOInstanzartLang;
    staff::Optional<std::string> AFKDONummer;
    staff::Optional<std::string> AFKDOName;
    staff::Optional<std::string> AFKDOInstanzartLang;
    staff::Optional<std::string> GemeindeName;
  };

  struct ArrayOfFdWsErreichbarkeitenFeuerwehrhaeuserStruct
  {
    // *itemName: FdWsErreichbarkeitenFeuerwehrhaeuserStruct
    // *useParentElement: true
    std::list< staff::Nillable< ::FdWsErreichbarkeitenFeuerwehrhaeuserStruct > > FdWsErreichbarkeitenFeuerwehrhaeuserStruct;
  };

  struct FdWsErreichbarkeitenFeuerwehrhaeuserStruct: public ::Writer
  {
    long FdiskIdFeuerwehrhaeuser;
    staff::Optional<std::string> Feuerwache;
    staff::Optional<std::string> InstanzNummer;
    staff::Optional<std::string> InstanzArt;
    staff::Optional<std::string> ErreichbarkeitArt;
    staff::Optional<std::string> Erreichbarkeit;
    staff::dateTime LetzteAenderung;
  };

  struct ArrayOfFdWsErreichbarkeitenPersonenStruct
  {
    // *itemName: FdWsErreichbarkeitenPersonenStruct
    // *useParentElement: true
    std::list< staff::Nillable< ::FdWsErreichbarkeitenPersonenStruct > > FdWsErreichbarkeitenPersonenStruct;
  };

  struct FdWsErreichbarkeitenPersonenStruct: public ::Writer
  {
    long FdiskIdPersonen;
    staff::Optional<std::string> ErreichbarkeitArt;
    staff::Optional<std::string> Erreichbarkeit;
    staff::dateTime LetzteAenderung;
  };

  struct ArrayOfFdWsFeuerwehrhaeuserStruct
  {
    // *itemName: FdWsFeuerwehrhaeuserStruct
    // *useParentElement: true
    std::list< staff::Nillable< ::FdWsFeuerwehrhaeuserStruct > > FdWsFeuerwehrhaeuserStruct;
  };

  struct FdWsFeuerwehrhaeuserStruct: public ::Writer
  {
    long FdiskIdFeuerwehrhaeuser;
    long FdiskIdFeuerwehren;
    long FdiskIdInstanzen;
    staff::Optional<std::string> Instanznummer;
    staff::Optional<std::string> Instanzname;
    staff::dateTime Gruendungsdatum;
    staff::Optional<std::string> Hausbezeichnung;
    staff::Optional<std::string> Strasse;
    staff::Optional<std::string> Nummer;
    staff::Optional<std::string> Stiege;
    staff::Optional<std::string> Kathastralgemeinde;
    staff::Optional<std::string> PLZ;
    staff::Optional<std::string> Ort;
    staff::Optional<std::string> ErreichbarkeitMail;
    staff::Optional<std::string> ErreichbarkeitMobil;
    staff::Optional<std::string> ErreichbarkeitFestnetz;
    staff::Optional<std::string> ErreichbarkeitFax;
    staff::Optional<std::string> ErreichbarkeitGruppenRic;
    staff::Optional<std::string> ErreichbarkeitUrl;
    staff::Optional<std::string> Koordinaten;
    staff::dateTime LetzteAenderung;
    staff::Optional<std::string> Feuerwache;
  };

  struct ArrayOfFdWsFeuerwehrGemeindenStruct
  {
    // *itemName: FdWsFeuerwehrGemeindenStruct
    // *useParentElement: true
    std::list< staff::Nillable< ::FdWsFeuerwehrGemeindenStruct > > FdWsFeuerwehrGemeindenStruct;
  };

  struct FdWsFeuerwehrGemeindenStruct: public ::Writer
  {
    long FdiskIdFwInstanzen;
    staff::Optional<std::string> FwNummer;
    staff::Optional<std::string> FwName;
    long FdiskIdGemInstanzen;
    staff::Optional<std::string> GemNummer;
    staff::Optional<std::string> GemName;
  };

  struct ArrayOfFdWsWasserdienstleistungsbewerbeStruct
  {
    // *itemName: FdWsWasserdienstleistungsbewerbeStruct
    // *useParentElement: true
    std::list< staff::Nillable< ::FdWsWasserdienstleistungsbewerbeStruct > > FdWsWasserdienstleistungsbewerbeStruct;
  };

  struct FdWsWasserdienstleistungsbewerbeStruct: public ::Writer
  {
    long FdiskIdBewerbsgruppen;
    staff::Optional<std::string> Durchgang;
    staff::Optional<std::string> Zillennummer;
    staff::Optional<std::string> Farbe;
    staff::Optional<std::string> Bewerbsbezeichnung;
    staff::Optional<std::string> Instanzname;
    staff::Optional<std::string> Wertungsklasse;
    staff::Optional<std::string> Alterspunkte;
    staff::Optional<std::string> AlterspunkteWert;
    staff::Optional<std::string> Name1;
    staff::Optional<std::string> Name2;
    staff::dateTime LetzteAenderung;
  };

  struct ArrayOfFdWsFeuerwehrleistungsbewerbeStruct
  {
    // *itemName: FdWsFeuerwehrleistungsbewerbeStruct
    // *useParentElement: true
    std::list< staff::Nillable< ::FdWsFeuerwehrleistungsbewerbeStruct > > FdWsFeuerwehrleistungsbewerbeStruct;
  };

  struct FdWsFeuerwehrleistungsbewerbeStruct: public ::Writer
  {
    long FdiskIdBewerbe;
    long FdiskIdPersonen;
    staff::Optional<std::string> DienstgradKurz;
    long FdiskIdBewerbsgruppen;
    staff::Optional<std::string> Bewerbsgruppe;
    long Bewerbsgruppennummer;
    staff::Optional<std::string> Bewerbsbezeichnung;
    staff::Optional<std::string> Instanzart;
    staff::Optional<std::string> Instanzname;
    staff::Optional<std::string> Bezirk;
    staff::Optional<std::string> Abschnitt;
    double ErreichtePunkte;
    staff::Optional<std::string> BewerbsgruppenStatus;
    staff::Optional<std::string> WertungsklasseLangBez;
    staff::Optional<std::string> Wertungsklasse;
    staff::Optional<std::string> Alterspunkte;
    staff::Optional<std::string> Titel;
    staff::Optional<std::string> Zuname;
    staff::Optional<std::string> Vorname;
    staff::Optional<std::string> Leistungsabzeichen;
    staff::Optional<std::string> Leistungsabzeichenstufe;
    staff::Optional<std::string> Bewerbsort;
    staff::dateTime Bewerbstag;
    staff::Optional<std::string> LFKKommandant;
    staff::Optional<std::string> BewerbsKommandant;
    staff::Optional<std::string> Bewerbsleiter;
    bool LeistungsabzeichenErhalten;
    staff::dateTime LetzteAenderung;
    staff::Optional< ::ArrayOfFdWsFeuerwehrleistungsbewerbePunkte > DetailPunkte;
  };

  struct ArrayOfFdWsFeuerwehrleistungsbewerbePunkte
  {
    // *itemName: FdWsFeuerwehrleistungsbewerbePunkte
    // *useParentElement: true
    std::list< staff::Nillable< ::FdWsFeuerwehrleistungsbewerbePunkte > > FdWsFeuerwehrleistungsbewerbePunkte;
  };

  struct FdWsFeuerwehrleistungsbewerbePunkte
  {
    staff::Optional<std::string> Bezeichnung;
    double Punkte;
  };

  struct FdWsAuthorizeReturn
  {
    staff::Optional<std::string> md5session;
    staff::Optional<std::string> statusMessage;
    ::StatusCodes statusCode;
  };


  //!  service FdExport
  // *serviceUri: https://app.fdisk.at/FDISK/schnittstellen/fdwebservice/export/fdexport.asmx
  // *soapVersion: 1.1
  // *targetNamespace: http://fdisk.at/
  class FdExport: public staff::IService
  {
  public:
    // *requestElement: PrepareData
    // *responseElement: PrepareDataResponse
    // *resultElement: PrepareDataResult
    // *soapAction: http://fdisk.at/PrepareData
    virtual staff::Optional< ::FdWsPrepareDataReturn > PrepareData(const staff::Optional<std::string>& md5session, const staff::Optional< ::FdWsPrepareDataRequest >& xmlRequest) = 0;

    // *requestElement: getNextDataBlock
    // *responseElement: getNextDataBlockResponse
    // *resultElement: getNextDataBlockResult
    // *soapAction: http://fdisk.at/getNextDataBlock
    virtual staff::Optional< ::FdWsGetNextDataBlockReturn > getNextDataBlock(const staff::Optional<std::string>& md5session) = 0;

    // *requestElement: Authorize
    // *responseElement: AuthorizeResponse
    // *resultElement: AuthorizeResult
    // *soapAction: http://fdisk.at/Authorize
    virtual staff::Optional< ::FdWsAuthorizeReturn > Authorize(const staff::Optional<std::string>& user, const staff::Optional<std::string>& password, const staff::Optional<std::string>& instanz) = 0;

    // *requestElement: closeSession
    // *responseElement: closeSessionResponse
    // *soapAction: http://fdisk.at/closeSession
    virtual void closeSession(const staff::Optional<std::string>& md5session) = 0;
  };


#endif // _FdExport_h_

